# Generated by Django 5.1.7 on 2025-04-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
