# Generated by Django 5.1.7 on 2025-04-23 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_poster'),
    ]

    operations = [
    ]
