# Generated by Django 5.1.7 on 2025-04-05 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='count',
        ),
    ]
